apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: amrit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 1Gi
